# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: dotnet-sdk
    directories:
      - src/*.csproj
      - test/*.csproj
    target-branch: dev
    assignees:
      - GGG-KILLER
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    assignees:
      - GGG-KILLER
    commit-message:
      prefix: ci
      include: scope
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: docker
    directory: /src
    target-branch: dev
    assignees:
      - GGG-KILLER
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: weekly
      day: friday
